---
kind: Namespace
apiVersion: v1
metadata:
  name: logging-kubernetes-using-loki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-deployment
  namespace: logging-kubernetes-using-loki
  labels:
    app: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
        - name: foo
          image: chentex/random-logger:latest
          resources:
            requests:
              memory: "20Mi"
              cpu: "20m"
            limits:
              memory: "50Mi"
              cpu: "50m"