# https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
grafana:
  sidecar:
    datasources:
      enabled: false
loki: # https://github.com/grafana/helm-charts/blob/main/charts/loki/values.yaml
  persistence:
    enabled: true
    size: "${LOG_STORAGE_SIZE}"
  config:
    ruler:
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      rule_path: /tmp/loki
      alertmanager_url: http://prometheus-kube-prometheus-alertmanager.svc.monitoring:9093
      ring:
        kvstore:
          store: inmemory
      enable_api: true
  extraVolumes:
    - name: loki-ruler-alerting-rules
      configMap:
        name: loki-ruler-alerting-rules
        optional: true
    - name: loki-ruler-recording-rules
      configMap:
        name: loki-ruler-recording-rules
        optional: true
  extraVolumeMounts:
    - name: loki-ruler-alerting-rules
      mountPath: "/etc/loki/rules/alerts"
    - name: loki-ruler-recording-rules
      mountPath: "/etc/loki/rules/records"
